---
# tasks file for HAproxyLB
- name: "installing the haproxy software into loadBalancer"
  package:
      name: "haproxy"
      state: present
- name: "copying the haproxy.cfg.j2 file to the loadBalancer"
  template:
      dest: "/etc/haproxy/haproxy.cfg"
      src: "haproxy.cfg.j2"
- name: "restarting the loadBalancer"
  service:
      name: "haproxy"
      state: restarted
