---
# tasks file for myapache
- name: "installing the httpd server"
  package:
     name: "httpd"
     state: present
- name: "installing the php on the webserver"
  package:
     name: "php"
     state: present
- name: "copying the content into webserver"
  copy:
     dest: "/var/www/html/index.php"
     src: "index.php"
- name: "starting the httpd"
  service:
     name: "httpd"
     state: started
